name: Deploy Devof Razor

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Stop service and prepare deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo systemctl stop devof
          sudo rm -rf /var/www/devof.net/*
          sudo chown -R $USER:$USER /var/www/devof.net

    - name: Upload files to production
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "out/**"
        target: "/var/www/devof.net"
        strip_components: 1

    - name: Start service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/devof.net
          sudo systemctl start devof
